MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
proj:
    - '9.0'
gdal:
    - '3.5'
geos:
    - '3.11'
qwt:
    - '6.2'
