{% set version = "3.32.0" %}

package:
  name: qgis
  version: {{ version }}

source:
  url: https://qgis.org/downloads/qgis-{{ version }}.tar.bz2
  sha256: dfc90a6103a3c6020d005dbb68c81caf9a4c11fca4be53bfe070226813f87a9a
  patches:
    # now need define on all platforms
    - 0001-use-protobuf-dlls.patch
    - 0002-skip-dot-in-path.patch  # [win]
    # remove when https://github.com/conda-forge/pyqt-feedstock/pull/129 merged
    - 0003-workaround-multi-pyqt5.patch  # [win]
    - 0004-wrench_threads.patch

build:
  number: 1
  #skip: true  # [(not win) or (not py==39)]
  skip: true  # [py2k or py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - ninja
    - m2-flex  # [win]
    - m2-bison  # [win]
    - m2-m4  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # The CDT packages below are those used in qt-feedstock
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('cups-devel') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - sip                                # [build_platform != target_platform]
    - pyqt-builder                       # [build_platform != target_platform]
    - pyqt5-sip                          # [build_platform != target_platform]
    - pyqt                               # [build_platform != target_platform]
    - qscintilla2                        # [build_platform != target_platform]
    - pkgconfig                          # [build_platform != target_platform]
    - flex                               # [unix and (build_platform != target_platform)]
    - bison                              # [unix and (build_platform != target_platform)]
    - m4                                 # [unix and (build_platform != target_platform)]
    - pdal                               # [build_platform != target_platform]
    - libprotobuf                        # [build_platform != target_platform]
  host:
    - setuptools
    - sip
    - python
    - six
    - flex                               # [unix]
    - bison                              # [unix]
    - m4                                 # [unix]
    - pkgconfig
    - expat
    - icu
    - libzip
    - libprotobuf
    - libtasn1  # [osx]
    - exiv2
    # Qt stack.
    - qt-main
    - pyqt
    - pyqt5-sip
    - pyqt-builder
    - qtwebkit
    - pyqtwebkit
    - qscintilla2
    - qca
    - qjson
    - qwt
    - qtkeychain
    # GDAL stack.
    - libgdal
    - gdal
    - geos
    - proj
    # GSL for georeferencer.
    - gsl
    - sqlite
    - libspatialindex
    - libspatialite
    # For PostgreSQL support.
    - postgresql
    - psycopg2
    # Point Clouds
    - pdal
    - laz-perf
  run:
    - python
    - icu
    - libzip
    - libtasn1  # [osx]
    - qt-main
    - pyqt
    - qtwebkit
    - qscintilla2
    - qca
    - qjson
    - qwt
    - qtkeychain
    - libgdal
    - gdal
    - geos
    - proj
    - gsl
    - sqlite
    - libspatialindex
    - libspatialite
    - psycopg2
    - postgresql
    - exiv2
    - libprotobuf
    # Runtime Python library deps
    - python-dateutil
    - future
    - httplib2
    - jinja2
    - markupsafe
    - mock
    - nose2
    - plotly
    - pygments
    - pyproj
    - requests
    - six
    - pytz
    - pyyaml
    - yaml
    - owslib
    - pyqtwebkit
    - pdal
    - laz-perf

  run_constrained:   # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]
test:
  requires:
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
  files:
    - test_data
    - test_py_qgis.py
  commands:
    - {{ RECIPE_DIR }}/run_test.bat  # [win]
    - bash {{ RECIPE_DIR }}/run_test.sh  # [not win]

about:
  home: http://qgis.org/
  license: GPL-2.0-only
  license_file: COPYING
  summary: A free and open source Geographic Information System (GIS).
  description: |
    QGIS is a user friendly Open Source Geographic Information System (GIS)
    licensed under the GNU General Public License. QGIS is an official
    project of the Open Source Geospatial Foundation (OSGeo). It runs on
    Linux, Unix, Mac OSX, Windows and Android and supports numerous vector,
    raster, and database formats and functionalities.
  doc_url: https://www.qgis.org/en/docs/index.html
  dev_url: https://github.com/qgis/QGIS

extra:
  recipe-maintainers:
    - ceholden
    - ocefpaf
    - kmuehlbauer
    - SrNetoChan
    - gillins
    - izahn
