{% set name = "qgis" %}
{% set version = "2.18.2" %}
{% set sha256 = "e218ecc2c0b983a95bba0dc46788661e803cf870f5740cbcfaa1ea39a71f02a0" %}

package:
  name: qgis
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://qgis.org/downloads/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    # QGIS inserts Qt plugin locations into PATH relative to build location
    # This patch fixes it so PATH is relative to install location
    - plugins_path.patch  # [linux]

build:
  number: 1
  skip: true  # [not linux or py3k]

requirements:
  build:
    - cmake
    - flex
    - bison
    - m4
    - python
    - sip
    - expat
    - icu 58.*
    # Qt stack.
    - qt 5.6.*
    - pyqt 5.6.*
    - qscintilla2
    - qca
    - qjson
    - qwt
    - qwtpolar
    # GDAL stack.
    - gdal 2.1.*
    - geos 3.5.*
    - proj4 4.9.3
    # GSL for georeferencer.
    - gsl
    - sqlite 3.13.*
    - libspatialindex
    - libspatialite
    # For PostgreSQL support.
    - postgresql
    - psycopg2
  run:
    - python
    - icu 58.*
    - qt 5.6.*
    - pyqt 5.6.*
    - qscintilla2
    - qca
    - qjson
    - qwt
    - qwtpolar
    - gdal 2.1.*
    - geos 3.5.*
    - proj4 4.9.3
    - gsl
    - sqlite 3.13.*
    - libspatialindex
    - libspatialite
    - psycopg2
    - postgresql
    # Runtime deps QGIS can include internally.
    - future
    - dateutil
    - httplib2
    - jinja2
    - markupsafe
    - nose
    - owslib
    - pygments
    - pytz
    - six
    - pyyaml
    - yaml

test:
  commands:
    - conda inspect linkages -p $PREFIX qgis  # [not win]
    - conda inspect objects -p $PREFIX qgis  # [osx]

about:
  home: http://qgis.org/
  license: GPL-2.0
  license_file: COPYING
  summary: 'A free and open source Geographic Information System (GIS).'
  description: |
    QGIS is a user friendly Open Source Geographic Information System (GIS)
    licensed under the GNU General Public License. QGIS is an official
    project of the Open Source Geospatial Foundation (OSGeo). It runs on
    Linux, Unix, Mac OSX, Windows and Android and supports numerous vector,
    raster, and database formats and functionalities.
  doc_url: https://www.qgis.org/en/docs/index.html
  dev_url: https://github.com/qgis/QGIS

extra:
  recipe-maintainers:
    - ceholden
    - ocefpaf
