travis:
  secure:
    BINSTAR_TOKEN: kAnXh0ND9xc5HNCkJwYZTr4H3uLk5p/BjaqrjmwvMKxajc5B6g5f8DAkAS5GOutx7aonRM5p0zXLo/z0zNBRrKTFqIwekiDBT2y2I16Rncymof7+XBgXy2rul5o59OE5YHNGVqFdFX5kSQ2pFOv7XarrvkLe50b+xkaL6crOp1q532B1pkn08VoojSZXMcha82YvzbpE166/Je9WgDFTGOBrYr2NJuIt5eEB53HJgTlvhux80mAj0Tzo2H0U9A7pNiK0/+rh4DupawVu+WxZxOJIL3L0DtfUR1dGkbGC0KAUA4x9hnjOZ9FoB693FYJEHGKDr8RmuPaq716LgpTiPcoSyRUZ02ZQM18PekLV8tfdHglSoiGzov7Vnm73B8PNKF/GzQ6p6ZxXuE0WXy8P0/ac74wykortpxvKambvRJA1JWZwMgXM6OQkej0pnJULbhb89Oo6XziELJ958XRGdWsvZs1Lyfje9QHzMh9xvMQrFPdVE4Kf9EuI4Dc77rvZuJVWk9nEJ2vRD2dpi2GdxE9A3KGm4S3/FG4ecS3KAhIR0bhnxLzUkwk/iSjOmMUNEblyObH2YNCIB6Wd875avzVd8TDHw2j3mkPfA70s3NBwojkU4D+awESjKAcXc6oVkwx4RuSwjG4Ymh5piXdQg3Ez/IzTA1ETlAHy3GIdP5I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
