provider:
  osx: azure
  linux: azure
  win: azure
conda_forge_output_validation: true
azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\bld\
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
conda_build:
  pkg_format: '2'
