bot:
  abi_migration_branches:
  - LTR
provider:
  osx: azure
  linux: azure
  win: azure
  linux_aarch64: azure
  linux_ppc64le: azure
conda_forge_output_validation: true
azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\bld\
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
conda_build:
  pkg_format: '2'
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
test_on_native_only: true

